name: tests-books

on:
  pull_request:
    paths:
      - 'books/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd books && npm install && npm run test:ci
